SET client_min_messages TO warning;

DROP TABLE IF EXISTS works CASCADE;
DROP TABLE IF EXISTS has_skill CASCADE;
DROP TABLE IF EXISTS requires CASCADE;
DROP TABLE IF EXISTS job CASCADE;
DROP TABLE IF EXISTS position CASCADE;
DROP TABLE IF EXISTS takes CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS teaches CASCADE;
DROP TABLE IF EXISTS skill CASCADE;
DROP TABLE IF EXISTS purchase CASCADE;
DROP TABLE IF EXISTS factory CASCADE;
DROP TABLE IF EXISTS course CASCADE;