insert into person values ('9', 'Smith', 'Alivia', '497 8th St. Camp Hill, PA', '17011', 'llaoulidia@piscosf.com', 'female');
insert into person values ('12', 'Johnson', 'Billie', '9786 Albany St. Muskegon, MI', '49441', 'eabhishe@crashkiller.ovh', 'female');
insert into person values ('2', 'Williams', 'Aries', '62 East Jones St. Lexington, NC', '27292', '0hesimli@dorne.ml', 'male');
insert into person values ('14', 'Jones', 'Birdee', '662 Madison Street Hampton, VA', '23666', '3karar.alftlaw@ca11.cf', 'female');
insert into person values ('16', 'Brown', 'Cage', '8811 Tailwater Dr. York, PA', '17402', '4die@harysetiabudi.site', 'male');
insert into skill values ('5','Java','Programming Language','advanced');
insert into skill values ('9','C','Low-level Programming Language','intermediate');
insert into skill values ('13','C++','Programming Language','intermediate');
insert into skill values ('0','C#','Scripting Language','advanced');
insert into skill values ('11','Python','Programming Language','beginner');
insert into skill values ('14','Visual Basic','Programming Language','beginner');
insert into skill values ('3','.NET Programming','Scripting Language','intermediate');
insert into skill values ('10','JavaScript','Scripting Language','intermediate');
insert into skill values ('16','JQuery','Query Language','beginner');
insert into skill values ('8','XML','Scripting Language','intermediate');
insert into skill values ('15','Ruby','Programming Language','beginner');
insert into skill values ('2','Perl','Programming Language','advanced');
insert into skill values ('1','VB Script','Scripting Language','intermediate');
insert into skill values ('18','Microsoft Windows','Operating System','intermediate');
insert into skill values ('6','Penetration-testing','Security','intermediate');
insert into skill values ('7','Encryption','Security','beginner');
insert into skill values ('12','Mobile Development','Development','beginner');
insert into skill values ('19','Network Configuration','Networking','advanced');
insert into skill values ('17','Forensics','Security','advanced');
insert into skill values ('4','Bioinformatics','Analyzing data','advanced');
insert into has_skill values ('9', '1');
insert into has_skill values ('9', '0');
insert into has_skill values ('12', '10');
insert into has_skill values ('12', '6');
insert into has_skill values ('2', '15');
insert into has_skill values ('2', '4');
insert into has_skill values ('2', '7');
insert into has_skill values ('14', '16');
insert into has_skill values ('14', '13');
insert into has_skill values ('16', '1');
insert into has_skill values ('16', '10');
insert into has_skill values ('16', '2');
insert into factory values ('14', 'Mineral Furnace', '3258 Chapel Street, NY', '01702', '504-884-6576', 'John');
insert into factory values ('8', 'Furnace Fire', '2743 Fairmont Avenue, CA', '10001', '619-702-9198', 'Dave');
insert into factory values ('2', 'Fortune Furnace', '4365 Wright Court, KY', '03101', '602-322-4702', 'Mike');
insert into factory values ('3', 'fac4', '2517 Lynn Avenue PA', '11968', '337-498-3531', 'Jesus');
insert into factory values ('13', 'fac5', '166 Progress Way TX', '41862', '850-951-5364', 'Goku');
insert into factory values ('0', 'fac6', '2799 Huntz Lane LA', '66666', '666-666-6666', 'Satan');
insert into position values ('6', 'Software Support', 'Intelligent, hard-working, creative customer focused support person', '70000', '50000');
insert into position values ('17', 'Software Developer', 'Experienced, self-motivated, and talented software engineer', '96000', '70000');
insert into position values ('4', 'PC Technician', 'Perform PC and 1st level network troubleshooting to isolate, diagnose and resolve common pc/network problems', '90000', '60000');
insert into position values ('18', 'Javascript Engineer', 'Design front-end webpages', '75000', '54000');
insert into position values ('10', 'Associate Director of Web Strategy', 'UI/ UX Rock Star that can not only create awesome themes, wireframes, and graphics - but code it into a responsive website', '95000', '80000');
insert into position values ('3', 'Cyber Security Specialist', 'Monitor network security and regularly pen-test the server. Advise the IT-team of secure design', '130000', '92000');
insert into position values ('7', 'Enterprise IT Service Help Desk', 'Sit at a desk and answer phone calls from customers', '60000', '40000');
insert into position values ('0', 'Medical Data Entry Genius', 'Entering medical data onto a database', '70000', '60000');
insert into position values ('8', 'Systems Librarian', 'Proficiency with standard computer hardware and desktop applications', '90000', '50000');
insert into position values ('14', 'Deputy Program Manager', 'Manages the connectivity of varius programs implemented', '100000', '63000');
insert into job values ('14', 'Information Technology', '3', '6', '2', 'full-time','33','wage','2','Auto Zone');
insert into job values ('6', 'Front-end', '3', '7', '14', 'full-time','50','wage','19','Auto Zone');
insert into job values ('13', 'Software Engineer', '13', '4', '2', 'part-time','90000','salary','9','Auto Zone');
insert into job values ('15', 'Software Engineer', '8', '0', '12', 'part-time','67','wage','7','Auto Zone');
insert into job values ('5', 'Back-end', '2', '18', '9', 'full-time','95000','salary','10','Auto Zone');
insert into job values ('4', 'Information Technology', '3', '6', '12', 'part-time','130000','salary','17','Auto Zone');
insert into job values ('17', 'Software Engineer', '14', '6', '2', 'full-time','31','wage','3','Auto Zone');
insert into job values ('12', 'Software Engineer', '13', '4', '9', 'part-time','70000','salary','16','Auto Zone');
insert into job values ('11', 'Front-end', '3', '6', '2', 'part-time','90000','salary','18','Auto Zone');
insert into job values ('9', 'Software Engineer', '14', '10', '12', 'full-time','100000','salary','8','Auto Zone');
insert into requires values ('3', '6');
insert into requires values ('19', '17');
insert into requires values ('10', '17');
insert into requires values ('13', '17');
insert into requires values ('14', '17');
insert into requires values ('18', '17');
insert into requires values ('2', '17');
insert into requires values ('3', '17');
insert into requires values ('12', '4');
insert into requires values ('0', '4');
insert into requires values ('3', '18');
insert into requires values ('6', '18');
insert into requires values ('5', '18');
insert into requires values ('19', '18');
insert into requires values ('0', '18');
insert into requires values ('18', '10');
insert into requires values ('5', '10');
insert into requires values ('17', '10');
insert into requires values ('19', '3');
insert into requires values ('8', '3');
insert into requires values ('0', '3');
insert into requires values ('18', '3');
insert into requires values ('5', '3');
insert into requires values ('17', '3');
insert into requires values ('2', '3');
insert into requires values ('5', '7');
insert into requires values ('9', '7');
insert into requires values ('17', '7');
insert into requires values ('8', '7');
insert into requires values ('5', '0');
insert into requires values ('18', '8');
insert into requires values ('4', '8');
insert into requires values ('12', '8');
insert into requires values ('15', '8');
insert into requires values ('4', '14');
insert into requires values ('3', '14');

