SET client_min_messages TO warning;

DROP TABLE IF EXISTS takes CASCADE;
DROP TABLE IF EXISTS teaches CASCADE;
DROP TABLE IF EXISTS course CASCADE;
DROP TABLE IF EXISTS works CASCADE;
DROP TABLE IF EXISTS has_skill CASCADE;
DROP TABLE IF EXISTS requires CASCADE;
DROP TABLE IF EXISTS job CASCADE;
DROP TABLE IF EXISTS position CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS sub_ind CASCADE;
DROP TABLE IF EXISTS GICS CASCADE;
DROP TABLE IF EXISTS company CASCADE;
DROP TABLE IF EXISTS skill CASCADE;