insert into person values ('2', 'Smith', 'Alivia', '497 8th St. Camp Hill, PA', '17011', 'llaoulidia@piscosf.com', 'female');
insert into person values ('4', 'Johnson', 'Billie', '9786 Albany St. Muskegon, MI', '49441', 'eabhishe@crashkiller.ovh', 'female');
insert into person values ('9', 'Williams', 'Aries', '62 East Jones St. Lexington, NC', '27292', '0hesimli@dorne.ml', 'male');
insert into person values ('13', 'Jones', 'Birdee', '662 Madison Street Hampton, VA', '23666', '3karar.alftlaw@ca11.cf', 'female');
insert into person values ('14', 'Brown', 'Cage', '8811 Tailwater Dr. York, PA', '17402', '4die@harysetiabudi.site', 'male');
insert into person values ('17', 'Kadic', 'Ammar', 'null', 'null', 'null', 'null');
insert into person values ('19', 'Fang', 'Andy', 'null', 'null', 'null', 'null');
insert into person values ('0', 'Brisco', 'Kenneth', 'null', 'null', 'null', 'null');
insert into person values ('5', 'Jameson', 'Jame', 'null', 'null', 'null', 'null');
insert into person values ('7', 'Jenkins', 'Leeroy', 'null', 'null', 'null', 'null');
insert into skill values ('13','Java','Programming Language','advanced');
insert into skill values ('15','C','Low-level Programming Language','beginner');
insert into skill values ('10','C++','Programming Language','intermediate');
insert into skill values ('0','C#','Scripting Language','intermediate');
insert into skill values ('8','Python','Programming Language','advanced');
insert into skill values ('4','Visual Basic','Programming Language','intermediate');
insert into skill values ('7','.NET Programming','Scripting Language','intermediate');
insert into skill values ('17','JavaScript','Scripting Language','advanced');
insert into skill values ('1','JQuery','Query Language','beginner');
insert into skill values ('9','XML','Scripting Language','intermediate');
insert into skill values ('5','Ruby','Programming Language','advanced');
insert into skill values ('11','Perl','Programming Language','beginner');
insert into skill values ('3','VB Script','Scripting Language','intermediate');
insert into skill values ('19','Microsoft Windows','Operating System','advanced');
insert into skill values ('2','Penetration-testing','Security','intermediate');
insert into skill values ('6','Encryption','Security','advanced');
insert into skill values ('14','Mobile Development','Development','advanced');
insert into skill values ('18','Network Configuration','Networking','beginner');
insert into skill values ('12','Forensics','Security','beginner');
insert into skill values ('16','Bioinformatics','Analyzing data','advanced');
insert into has_skill values ('2', '11');
insert into has_skill values ('2', '3');
insert into has_skill values ('2', '18');
insert into has_skill values ('2', '6');
insert into has_skill values ('4', '14');
insert into has_skill values ('4', '18');
insert into has_skill values ('4', '15');
insert into has_skill values ('4', '7');
insert into has_skill values ('4', '11');
insert into has_skill values ('9', '11');
insert into has_skill values ('9', '6');
insert into has_skill values ('9', '12');
insert into has_skill values ('9', '9');
insert into has_skill values ('9', '18');
insert into has_skill values ('13', '5');
insert into has_skill values ('13', '12');
insert into has_skill values ('13', '13');
insert into has_skill values ('13', '18');
insert into has_skill values ('13', '17');
insert into has_skill values ('13', '4');
insert into has_skill values ('13', '3');
insert into has_skill values ('13', '19');
insert into has_skill values ('13', '11');
insert into has_skill values ('14', '10');
insert into has_skill values ('14', '12');
insert into has_skill values ('17', '1');
insert into has_skill values ('17', '9');
insert into has_skill values ('17', '19');
insert into has_skill values ('17', '7');
insert into has_skill values ('19', '13');
insert into has_skill values ('19', '3');
insert into has_skill values ('19', '1');
insert into has_skill values ('0', '16');
insert into has_skill values ('0', '10');
insert into has_skill values ('0', '1');
insert into has_skill values ('0', '7');
insert into has_skill values ('0', '8');
insert into has_skill values ('0', '9');
insert into has_skill values ('5', '9');
insert into has_skill values ('5', '10');
insert into has_skill values ('5', '6');
insert into has_skill values ('5', '3');
insert into has_skill values ('5', '13');
insert into has_skill values ('5', '4');
insert into has_skill values ('5', '2');
insert into has_skill values ('5', '12');
insert into has_skill values ('5', '14');
insert into has_skill values ('7', '6');
insert into has_skill values ('7', '9');
insert into has_skill values ('7', '12');
insert into has_skill values ('7', '3');
insert into has_skill values ('7', '2');
insert into has_skill values ('7', '14');
insert into company values ('0', '1321', '3258 Chapel Street, NY', '01702', null);
insert into company values ('12', '2321', '2743 Fairmont Avenue, CA', '10001', null);
insert into company values ('2', '1321', '4365 Wright Court, KY', '03101', null);
insert into company values ('19', '3321', '2517 Lynn Avenue PA', '11968', null);
insert into company values ('4', '3321', '166 Progress Way TX', '41862', null);
insert into company values ('11', '2321', '2799 Huntz Lane LA', '66666', null);
insert into position values ('18', 'Software Support', 'Intelligent, hard-working, creative customer focused support person', '70000', '50000');
insert into position values ('2', 'Software Developer', 'Experienced, self-motivated, and talented software engineer', '96000', '70000');
insert into position values ('8', 'PC Technician', 'Perform PC and 1st level network troubleshooting to isolate, diagnose and resolve common pc/network problems', '90000', '60000');
insert into position values ('12', 'Javascript Engineer', 'Design front-end webpages', '75000', '54000');
insert into position values ('14', 'Associate Director of Web Strategy', 'UI/ UX Rock Star that can not only create awesome themes, wireframes, and graphics - but code it into a responsive website', '95000', '80000');
insert into position values ('19', 'Cyber Security Specialist', 'Monitor network security and regularly pen-test the server. Advise the IT-team of secure design', '130000', '92000');
insert into position values ('9', 'Enterprise IT Service Help Desk', 'Sit at a desk and answer phone calls from customers', '60000', '40000');
insert into position values ('10', 'Medical Data Entry Genius', 'Entering medical data onto a database', '70000', '60000');
insert into position values ('4', 'Systems Librarian', 'Proficiency with standard computer hardware and desktop applications', '90000', '50000');
insert into position values ('11', 'Deputy Program Manager', 'Manages the connectivity of varius programs implemented', '100000', '63000');
insert into job values ('2', 'Information Technology', '19', '9', 'full-time','33','wage','14');
insert into job values ('1', 'Information Technology', '2', '2', 'part-time','50','wage','8');
insert into job values ('12', 'Software Engineer', '19', '4', 'part-time','90000','salary','13');
insert into job values ('8', 'Back-end', '19', '4', 'part-time','67','wage','18');
insert into job values ('16', 'Front-end', '2', '8', 'part-time','95000','salary','11');
insert into job values ('17', 'Software Engineer', '12', '18', 'part-time','130000','salary','17');
insert into job values ('9', 'Back-end', '12', '2', 'part-time','31','wage','7');
insert into job values ('13', 'Back-end', '12', '10', 'part-time','70000','salary','10');
insert into job values ('0', 'Software Engineer', '12', '4', 'part-time','90000','salary','19');
insert into job values ('11', 'Front-end', '2', '2', 'full-time','100000','salary','3');
insert into requires values ('17', '18');
insert into requires values ('5', '18');
insert into requires values ('3', '18');
insert into requires values ('8', '18');
insert into requires values ('16', '18');
insert into requires values ('9', '18');
insert into requires values ('1', '18');
insert into requires values ('8', '2');
insert into requires values ('9', '2');
insert into requires values ('8', '8');
insert into requires values ('14', '8');
insert into requires values ('0', '8');
insert into requires values ('13', '8');
insert into requires values ('5', '8');
insert into requires values ('19', '8');
insert into requires values ('3', '12');
insert into requires values ('17', '12');
insert into requires values ('5', '12');
insert into requires values ('11', '12');
insert into requires values ('14', '12');
insert into requires values ('0', '14');
insert into requires values ('12', '14');
insert into requires values ('8', '14');
insert into requires values ('10', '14');
insert into requires values ('19', '14');
insert into requires values ('4', '14');
insert into requires values ('2', '14');
insert into requires values ('12', '19');
insert into requires values ('7', '9');
insert into requires values ('16', '10');
insert into requires values ('8', '10');
insert into requires values ('10', '10');
insert into requires values ('0', '4');
insert into requires values ('19', '4');
insert into requires values ('4', '4');
insert into requires values ('16', '4');
insert into requires values ('5', '11');
insert into works values ('5', '1', '2016', '11', '20', '2006', '11', '2');
insert into works values ('7', '12', '2018', '6', '14', '2007', '10', '29');
insert into works values ('17', '2', '2017', '6', '12', '2005', '1', '25');
insert into works values ('14', '13', '2017', '3', '10', '2006', '10', '16');
insert into works values ('4', '8', '2018', '2', '28', '2005', '5', '15');
insert into works values ('2', '0', '2016', '9', '7', '2010', '6', '1');
insert into works values ('4', '2', '2016', '12', '26', '2005', '6', '6');
insert into works values ('2', '9', '2019', '2', '4', '2009', '12', '9');
insert into works values ('5', '12', '2018', '7', '13', '2009', '10', '10');
insert into works values ('7', '17', '2015', '4', '4', '2005', '7', '6');
insert into works values ('9', '2', null, null, null, null, null, null);
insert into works values ('19', '16', null, null, null, null, null, null);
insert into works values ('5', '11', null, null, null, null, null, null);
insert into works values ('13', '1', null, null, null, null, null, null);
insert into works values ('13', '2', null, null, null, null, null, null);
insert into works values ('5', '9', null, null, null, null, null, null);
insert into works values ('17', '9', null, null, null, null, null, null);
insert into works values ('17', '0', null, null, null, null, null, null);
insert into works values ('2', '2', null, null, null, null, null, null);
insert into works values ('0', '13', null, null, null, null, null, null);
insert into GICS values ('1321', 'ind_1', '0', 'this is ind_1', '1321');
insert into GICS values ('2321', 'ind_2', '1', 'this is ind_2', '1321');
insert into GICS values ('3321', 'ind_3', '2', 'this is ind_3', '1321');
insert into course values ('3', 'General Networking', '1', 'Obtain a good understanding of how networks works', 'expired', null);
insert into course values ('10', 'IT Management', '1', 'Based on learning how to teach someone how to lead a team to completing a task in a quick manner', 'active', null);
insert into course values ('8', 'JAVA', '1', 'Understanding the major factors  of JAVA', 'active', null);
insert into course values ('18', 'JavaScript and jQuery', '2', 'Learn the ends and out on JavaScript and jQuery', 'expired', null);
insert into course values ('0', 'Cybersecurity', '4', 'Learn How To Prevent Vulnerabilities by becoming a white hat hacker', 'active', null);
insert into course values ('16', 'Database Administration', '3', 'Learn the final ends and outs of management and databases', 'active', null);
insert into course values ('1', 'Sales Management', '2', 'Learn how make the most profit', 'expired', null);
insert into course values ('13', 'Project Management Software', '5', 'Learning the minor things people usually miss and continue to improve your managent', 'active', null);
insert into course values ('4', 'Enterprise Resource Planning', '3', 'Learn how to properly plan events', 'active', null);
insert into course values ('17', 'C And C++', '4', 'Learn the importance of C and C++ and how to code general databases with these two languages', 'expired', null);
insert into teaches values ('3', '18');
insert into teaches values ('3', '19');
insert into teaches values ('10', '18');
insert into teaches values ('10', '1');
insert into teaches values ('8', '16');
insert into teaches values ('8', '10');
insert into teaches values ('18', '18');
insert into teaches values ('18', '3');
insert into teaches values ('0', '1');
insert into teaches values ('0', '15');
insert into teaches values ('16', '19');
insert into teaches values ('16', '15');
insert into teaches values ('1', '15');
insert into teaches values ('1', '12');
insert into teaches values ('13', '19');
insert into teaches values ('13', '5');
insert into teaches values ('4', '18');
insert into teaches values ('4', '4');
insert into teaches values ('17', '17');
insert into teaches values ('17', '9');
insert into sub_ind values ('0', '1321');
insert into sub_ind values ('12', '1321');
insert into sub_ind values ('2', '2321');
insert into sub_ind values ('19', '2321');
insert into sub_ind values ('4', '3321');
insert into sub_ind values ('11', '3321');
