insert into person values ('6', 'Smith', 'Alivia', '497 8th St. Camp Hill, PA', '17011', 'llaoulidia@piscosf.com', 'female');
insert into person values ('5', 'Johnson', 'Billie', '9786 Albany St. Muskegon, MI', '49441', 'eabhishe@crashkiller.ovh', 'female');
insert into person values ('4', 'Williams', 'Aries', '62 East Jones St. Lexington, NC', '27292', '0hesimli@dorne.ml', 'male');
insert into person values ('8', 'Jones', 'Birdee', '662 Madison Street Hampton, VA', '23666', '3karar.alftlaw@ca11.cf', 'female');
insert into person values ('1', 'Brown', 'Cage', '8811 Tailwater Dr. York, PA', '17402', '4die@harysetiabudi.site', 'male');
insert into skill values ('6','Java','Programming Language','beginner');
insert into skill values ('19','C','Low-level Programming Language','beginner');
insert into skill values ('2','C++','Programming Language','advanced');
insert into skill values ('16','C#','Scripting Language','beginner');
insert into skill values ('13','Python','Programming Language','beginner');
insert into skill values ('17','Visual Basic','Programming Language','intermediate');
insert into skill values ('9','.NET Programming','Scripting Language','advanced');
insert into skill values ('1','JavaScript','Scripting Language','advanced');
insert into skill values ('15','JQuery','Query Language','advanced');
insert into skill values ('7','XML','Scripting Language','intermediate');
insert into skill values ('3','Ruby','Programming Language','advanced');
insert into skill values ('18','Perl','Programming Language','beginner');
insert into skill values ('12','VB Script','Scripting Language','beginner');
insert into skill values ('8','Microsoft Windows','Operating System','intermediate');
insert into skill values ('0','Penetration-testing','Security','intermediate');
insert into skill values ('5','Encryption','Security','advanced');
insert into skill values ('4','Mobile Development','Development','beginner');
insert into skill values ('14','Network Configuration','Networking','advanced');
insert into skill values ('10','Forensics','Security','advanced');
insert into skill values ('11','Bioinformatics','Analyzing data','intermediate');
insert into has_skill values ('6', '3');
insert into has_skill values ('6', '18');
insert into has_skill values ('6', '8');
insert into has_skill values ('6', '4');
insert into has_skill values ('6', '2');
insert into has_skill values ('6', '1');
insert into has_skill values ('6', '17');
insert into has_skill values ('6', '16');
insert into has_skill values ('5', '17');
insert into has_skill values ('5', '6');
insert into has_skill values ('5', '4');
insert into has_skill values ('5', '12');
insert into has_skill values ('5', '16');
insert into has_skill values ('5', '7');
insert into has_skill values ('4', '14');
insert into has_skill values ('4', '1');
insert into has_skill values ('4', '18');
insert into has_skill values ('4', '3');
insert into has_skill values ('8', '4');
insert into has_skill values ('8', '16');
insert into has_skill values ('8', '5');
insert into has_skill values ('8', '19');
insert into has_skill values ('8', '8');
insert into has_skill values ('1', '11');
insert into has_skill values ('1', '6');
insert into has_skill values ('1', '12');
insert into company values ('1', '2321', '3258 Chapel Street, NY', '01702', null);
insert into company values ('18', '3321', '2743 Fairmont Avenue, CA', '10001', null);
insert into company values ('6', '2321', '4365 Wright Court, KY', '03101', null);
insert into company values ('4', '2321', '2517 Lynn Avenue PA', '11968', null);
insert into company values ('8', '2321', '166 Progress Way TX', '41862', null);
insert into company values ('0', '1321', '2799 Huntz Lane LA', '66666', null);
insert into position values ('2', 'Software Support', 'Intelligent, hard-working, creative customer focused support person', '70000', '50000');
insert into position values ('7', 'Software Developer', 'Experienced, self-motivated, and talented software engineer', '96000', '70000');
insert into position values ('16', 'PC Technician', 'Perform PC and 1st level network troubleshooting to isolate, diagnose and resolve common pc/network problems', '90000', '60000');
insert into position values ('12', 'Javascript Engineer', 'Design front-end webpages', '75000', '54000');
insert into position values ('9', 'Associate Director of Web Strategy', 'UI/ UX Rock Star that can not only create awesome themes, wireframes, and graphics - but code it into a responsive website', '95000', '80000');
insert into position values ('5', 'Cyber Security Specialist', 'Monitor network security and regularly pen-test the server. Advise the IT-team of secure design', '130000', '92000');
insert into position values ('13', 'Enterprise IT Service Help Desk', 'Sit at a desk and answer phone calls from customers', '60000', '40000');
insert into position values ('3', 'Medical Data Entry Genius', 'Entering medical data onto a database', '70000', '60000');
insert into position values ('4', 'Systems Librarian', 'Proficiency with standard computer hardware and desktop applications', '90000', '50000');
insert into position values ('1', 'Deputy Program Manager', 'Manages the connectivity of varius programs implemented', '100000', '63000');
insert into job values ('10', 'Front-end', '8', '5', 'full-time','33','wage','19');
insert into job values ('2', 'Software Engineer', '4', '12', 'full-time','50','wage','4');
insert into job values ('15', 'Back-end', '4', '16', 'full-time','90000','salary','3');
insert into job values ('0', 'Front-end', '4', '4', 'full-time','67','wage','13');
insert into job values ('19', 'Front-end', '8', '12', 'full-time','95000','salary','17');
insert into job values ('3', 'Information Technology', '1', '16', 'part-time','130000','salary','15');
insert into job values ('8', 'Front-end', '8', '7', 'full-time','31','wage','14');
insert into job values ('13', 'Back-end', '6', '5', 'full-time','70000','salary','16');
insert into job values ('7', 'Front-end', '18', '1', 'part-time','90000','salary','12');
insert into job values ('4', 'Back-end', '18', '4', 'part-time','100000','salary','6');
insert into requires values ('2', '2');
insert into requires values ('8', '2');
insert into requires values ('5', '2');
insert into requires values ('18', '2');
insert into requires values ('17', '2');
insert into requires values ('6', '7');
insert into requires values ('3', '7');
insert into requires values ('11', '7');
insert into requires values ('2', '7');
insert into requires values ('10', '7');
insert into requires values ('9', '7');
insert into requires values ('4', '7');
insert into requires values ('15', '16');
insert into requires values ('1', '16');
insert into requires values ('11', '16');
insert into requires values ('17', '16');
insert into requires values ('8', '16');
insert into requires values ('12', '16');
insert into requires values ('14', '12');
insert into requires values ('4', '12');
insert into requires values ('15', '12');
insert into requires values ('8', '12');
insert into requires values ('11', '12');
insert into requires values ('10', '12');
insert into requires values ('7', '12');
insert into requires values ('15', '9');
insert into requires values ('8', '9');
insert into requires values ('19', '9');
insert into requires values ('3', '9');
insert into requires values ('11', '5');
insert into requires values ('9', '5');
insert into requires values ('19', '5');
insert into requires values ('7', '5');
insert into requires values ('17', '13');
insert into requires values ('5', '13');
insert into requires values ('12', '3');
insert into requires values ('6', '4');
insert into requires values ('1', '4');
insert into requires values ('17', '1');
insert into requires values ('18', '1');
insert into requires values ('3', '1');
insert into requires values ('6', '1');
insert into requires values ('7', '1');
insert into works values ('8', '10', '2016', '2', '12', '2005', '12', '28');
insert into works values ('8', '0', '2016', '4', '11', '2007', '9', '1');
insert into works values ('4', '15', '2018', '6', '20', '2007', '6', '23');
insert into works values ('4', '7', '2017', '6', '29', '2011', '10', '6');
insert into works values ('5', '3', '2019', '8', '11', '2008', '3', '19');
insert into works values ('6', '13', '2019', '9', '12', '2010', '0', '3');
insert into works values ('6', '8', '2018', '3', '7', '2008', '5', '19');
insert into works values ('8', '7', '2014', '7', '6', '2007', '5', '2');
insert into works values ('8', '10', '2015', '0', '4', '2005', '5', '14');
insert into works values ('8', '2', '2019', '9', '3', '2008', '4', '19');
insert into works values ('8', '10', null, null, null, null, null, null);
insert into works values ('6', '19', null, null, null, null, null, null);
insert into works values ('6', '3', null, null, null, null, null, null);
insert into works values ('1', '15', null, null, null, null, null, null);
insert into works values ('6', '13', null, null, null, null, null, null);
insert into works values ('6', '2', null, null, null, null, null, null);
insert into works values ('4', '2', null, null, null, null, null, null);
insert into works values ('8', '10', null, null, null, null, null, null);
insert into works values ('6', '19', null, null, null, null, null, null);
insert into works values ('5', '8', null, null, null, null, null, null);
insert into GICS values ('1321', 'ind_1', '0', 'this is ind_1', '1321');
insert into GICS values ('2321', 'ind_2', '1', 'this is ind_2', '1321');
insert into GICS values ('3321', 'ind_3', '2', 'this is ind_3', '1321');
insert into course values ('2', 'General Networking', '1', 'Obtain a good understanding of how networks works', 'expired', null);
insert into course values ('9', 'IT Management', '1', 'Based on learning how to teach someone how to lead a team to completing a task in a quick manner', 'expired', null);
insert into course values ('15', 'JAVA', '1', 'Understanding the major factors  of JAVA', 'expired', null);
insert into course values ('8', 'JavaScript and jQuery', '2', 'Learn the ends and out on JavaScript and jQuery', 'active', null);
insert into course values ('13', 'Cybersecurity', '4', 'Learn How To Prevent Vulnerabilities by becoming a white hat hacker', 'expired', null);
insert into course values ('5', 'Database Administration', '3', 'Learn the final ends and outs of management and databases', 'active', null);
insert into course values ('16', 'Sales Management', '2', 'Learn how make the most profit', 'expired', null);
insert into course values ('0', 'Project Management Software', '5', 'Learning the minor things people usually miss and continue to improve your managent', 'active', null);
insert into course values ('10', 'Enterprise Resource Planning', '3', 'Learn how to properly plan events', 'expired', null);
insert into course values ('12', 'C And C++', '4', 'Learn the importance of C and C++ and how to code general databases with these two languages', 'active', null);
insert into teaches values ('2', '19');
insert into teaches values ('2', '4');
insert into teaches values ('9', '10');
insert into teaches values ('9', '8');
insert into teaches values ('15', '6');
insert into teaches values ('15', '11');
insert into teaches values ('8', '19');
insert into teaches values ('8', '13');
insert into teaches values ('13', '5');
insert into teaches values ('13', '19');
insert into teaches values ('5', '7');
insert into teaches values ('5', '18');
insert into teaches values ('16', '9');
insert into teaches values ('16', '16');
insert into teaches values ('0', '13');
insert into teaches values ('0', '16');
insert into teaches values ('10', '12');
insert into teaches values ('10', '3');
insert into teaches values ('12', '19');
insert into teaches values ('12', '15');
insert into sub_ind values ('1', '1321');
insert into sub_ind values ('18', '1321');
insert into sub_ind values ('6', '2321');
insert into sub_ind values ('4', '2321');
insert into sub_ind values ('8', '3321');
insert into sub_ind values ('0', '3321');
